export const COMMON_ITEMS = [
  'Tomatoes',
  'Onions',
  'Potatoes',
  'Garlic',
  'Ginger',
  'Chillies',
  'Cooking Oil',
  'Rice',
  'Daal (Lentils)',
  'Maida (Flour)',
  'Salt',
  'Sugar',
  'Masala (Spices)',
  'Turmeric Powder',
  'Cumin Seeds',
  'Coriander',
  'Chicken Meat',
  'Eggs',
  'Milk',
  'Butter',
  'Cheese',
  'Water (Gallon)',
  'LPG Gas',
  'Dish Soap',
  'Laundry Detergent',
  'Toilet Paper',
  'Broom / Mop',
  'Vegetables (Mixed)',
  'Fruits',
  'Noodles / Pasta',
  'Bread',
  'Tea / Coffee',
  'Other',
];
